### ISSUE TITLE
Getting RuntimeError "Contenxt is incorrect.". Facing this issue while applying the "triangulate" modifier.

### ISSUE THREAD

**Issue by Lovepreet94** [przemir/ApplyModifierForObjectWithShapeKeys#30]
`Python: Traceback (most recent call last):
  File "C:\Users\Lavi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ApplyModifierForObjectWithShapeKeys.py", line 260, in execute
    success, errorInfo = applyModifierForObjectWithShapeKeys(context, selectedModifiers, self.disable_armatures)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lavi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ApplyModifierForObjectWithShapeKeys.py", line 149, in applyModifierForObjectWithShapeKeys
    bpy.ops.object.shape_key_remove()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.object.shape_key_remove.poll() failed, context is incorrect
`

**Comment by przemir** [comment]
I cannot reproduce this error on Blender 4.02, 4.1 and 4.2 .

**Comment by Lovepreet94** [comment]
Resolved: My fault! I applied the shape key with the cursor outside the 3D viewport. Make sure you're in the 3D viewport when running the add-on.
